"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { fetchFeed, type Listing, type ListingType } from "@/lib/listings";
import { auth } from "@/lib/firebase";

interface UseFeedOptions {
  type?: ListingType;
  pageSize?: number;
}

interface UseFeedState {
  listings: Listing[];
  loading: boolean;
  loadingMore: boolean;
  error: string | null;
  exhausted: boolean;
  loadMore: () => void;
  reset: () => void;
}

// Mirrors mpRenderCards' pagination contract: seed is generated by the
// server on first call and must be echoed back on every subsequent page
// so the shuffle stays stable within a session. cursor is an opaque
// per-type offset object, also echoed back verbatim (not real Firestore
// pagination — see handleFeed in _handler.js).
export function useFeed({ type, pageSize = 24 }: UseFeedOptions = {}): UseFeedState {
  const [listings, setListings] = useState<Listing[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadingMore, setLoadingMore] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [exhausted, setExhausted] = useState(false);

  const seedRef = useRef<number | undefined>(undefined);
  const cursorRef = useRef<Record<string, number> | undefined>(undefined);
  const inFlight = useRef(false);

  const load = useCallback(
    async (isInitial: boolean) => {
      if (inFlight.current) return;
      inFlight.current = true;
      isInitial ? setLoading(true) : setLoadingMore(true);
      setError(null);
      try {
        const idToken = auth.currentUser ? await auth.currentUser.getIdToken() : null;
        const res = await fetchFeed({
          seed: seedRef.current,
          cursor: cursorRef.current,
          pageSize,
          type,
          idToken,
        });
        seedRef.current = res.seed;
        cursorRef.current = res.cursor;
        setExhausted(res.exhausted);
        setListings((prev) => (isInitial ? res.listings : [...prev, ...res.listings]));
      } catch (err: any) {
        setError(err?.message || "Failed to load listings");
      } finally {
        inFlight.current = false;
        isInitial ? setLoading(false) : setLoadingMore(false);
      }
    },
    [pageSize, type]
  );

  const reset = useCallback(() => {
    seedRef.current = undefined;
    cursorRef.current = undefined;
    setListings([]);
    setExhausted(false);
    load(true);
  }, [load]);

  useEffect(() => {
    reset();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [type]);

  const loadMore = useCallback(() => {
    if (exhausted || loading || loadingMore) return;
    load(false);
  }, [exhausted, loading, loadingMore, load]);

  return { listings, loading, loadingMore, error, exhausted, loadMore, reset };
}
